"""Added initial table

Revision ID: 89f6d0256a18
Revises: 463e687e1a0f
Create Date: 2023-02-22 10:15:26.231564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f6d0256a18'
down_revision = '463e687e1a0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
