"""Added initial table

Revision ID: dfc1d434e585
Revises: e821b7b1c627
Create Date: 2023-02-25 16:34:45.433336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc1d434e585'
down_revision = 'e821b7b1c627'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
