"""Added initial table

Revision ID: e821b7b1c627
Revises: 50feb265a851
Create Date: 2023-02-25 16:27:04.573994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e821b7b1c627'
down_revision = '50feb265a851'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_correct', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'is_correct')
    # ### end Alembic commands ###
